### PR TITLE
Correctly remove old measures when downloading new ones

### LINKED ISSUE #696: Local copy of BCL folder gets wiped/overwritten
Issue overview
--------------

Often, when I am adding a measure from the BCL online, it asks me to update my local files with the latest.  When I click ok, it completely wipes all of my local BCL files from the BCL folder and I am left with just the one or two that I just downloaded.  I then have to search for and redownload all of the measures that I previously had.

## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
image

### Context

This is a major hassle.

### PR DESCRIPTION
**Pull request by macumber**
Properly remove components and measures of the old version, add missing pngs to qrc, don't remove all old measures after updating measures

Fixes #696 

Behavior will be further improved with https://github.com/NREL/OpenStudio/pull/5127

### CODE REVIEW

**Comment by macumber** [comment]
@jmarrec I'll test this some more before merging, let me know if you have any objections, it is in code near some of your changes.

File: src/openstudio_lib/OSDocument.cpp [hunk 1]
```diff
@@ -1406,6 +1406,19 @@ boost::optional<BCLMeasure> OSDocument::getLocalMeasure(const std::string& uid,
   return result;
 }
 
+std::vector<BCLComponent> OSDocument::getLocalComponents() const {
+  std::vector<BCLComponent> result;
+  if (m_haveLocalBCL) {
```
Comment (jmarrec) [inline src/openstudio_lib/OSDocument.cpp:1411]: (I'm always thrown off by this ("Why would local bcl not be available") until I remember why we added it... )

File: src/openstudio_lib/OSDocument.cpp [hunk 2]
```diff
@@ -1406,6 +1406,19 @@ boost::optional<BCLMeasure> OSDocument::getLocalMeasure(const std::string& uid,
   return result;
 }
 
+std::vector<BCLComponent> OSDocument::getLocalComponents() const {
```
Comment (jmarrec) [inline src/openstudio_lib/OSDocument.cpp:1409]: I don't see why we need this.

File: src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp [hunk 3]
```diff
@@ -287,10 +287,12 @@ void BuildingComponentDialogCentralWidget::comboBoxIndexChanged(const QString& t
...
-    // remove old component
-    boost::optional<BCLComponent> oldComponent = OSAppBase::instance()->currentDocument()->getLocalComponent(component->uid());
-    if (oldComponent && oldComponent->versionId() != component->versionId()) {
-      LocalBCL::instance().removeComponent(*oldComponent);
+
+    // remove old components
+    for (auto& oldComponent : OSAppBase::instance()->currentDocument()->getLocalComponents()) {
+      if ((oldComponent.uid() == component->uid()) && (oldComponent.versionId() != component->versionId())) {
+        LocalBCL::instance().removeComponent(oldComponent);
+      }
```
Comment (jmarrec) [inline src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp:295]: Why is looping on all components as opposed to using getLocalComponent(uid) better/needed?!

File: src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp [hunk 4]
```diff
@@ -306,11 +308,13 @@ void BuildingComponentDialogCentralWidget::measureDownloadComplete(const std::st
...
 
-    // remove old measure
-    boost::optional<BCLMeasure> oldMeasure = OSAppBase::instance()->currentDocument()->getLocalMeasure(measure->uid());
-    if (oldMeasure && oldMeasure->versionId() != measure->versionId()) {
-      LocalBCL::instance().removeMeasure(*oldMeasure);
+    // remove old measures
+    for (auto& oldMeasure : OSAppBase::instance()->currentDocument()->getLocalMeasures()) {
+      if ((oldMeasure.uid() == measure->uid()) && (oldMeasure.versionId() != measure->versionId())) {
+        LocalBCL::instance().removeMeasure(oldMeasure);
+      }
```
Comment (jmarrec) [inline src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp:315]: Same question

File: src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp (hunk 3 above)
Comment (jmarrec) [reply src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp:295]: Oh, I think I see. getComponent(uid) returns the first it finds, is that it?

File: src/shared_gui_components/MeasureManager.cpp [hunk 5]
```diff
@@ -981,9 +981,6 @@ void MeasureManager::checkForRemoteBCLUpdates() {
     int result = msg.exec();
     if (result == QMessageBox::Yes) {
       remoteBCL.updateMeasures();
-      for (auto& oldMeasure : oldMeasures) {
-        LocalBCL::instance().removeMeasure(oldMeasure);
-      }
```
Comment (jmarrec) [inline src/shared_gui_components/MeasureManager.cpp:986]: So that's the actual fix? There's similar code a dozen lines below though.

File: src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp (hunk 3 above)
Comment (jmarrec) [reply src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp:295]: I want to move this logic inside OSDocument where we do check if local bcl is available.

Comment (macumber) [reply src/shared_gui_components/BuildingComponentDialogCentralWidget.cpp:295]: Yeah, we should just add new methods to OSDocument similar to what you added in https://github.com/NREL/OpenStudio/pull/5129.  We can update those to call the new methods when they become available.

File: src/shared_gui_components/MeasureManager.cpp (hunk 5 above)
Comment (macumber) [reply src/shared_gui_components/MeasureManager.cpp:986]: If `remoteBCL.updateMeasures();` works correctly then it will remove the outdated measures.  However, that wasn't working reliably due to the issue you fixed in https://github.com/NREL/OpenStudio/pull/5129.  My guess is that I was seeing a case where the old measures weren't removed so I added this code in.  However, this code fails when the new measures aren't fetched for some reason, the old ones will just be cleared.  I assumed that is what was happening in the bug report.
