### PR TITLE
Fix #747 - crash shoebox

### LINKED ISSUE #747: [v1.8.0-rc3] Opening Shoebox Model several times in a row produces a crash
Issue overview
--------------

On mac I had to do it like 3 or 4 times in row, on Ubuntu 20.04 I just had to it like 15 times before I could produce a crash.

This is likely the same issue I reported when I added "Load Example Model" in https://github.com/openstudiocoalition/OpenStudioApplication/pull/344 and that we probably never really fixed, even though @macumber tried a few things

<details>

<summary>Log and backtrace on Ubuntu 20.04 (built Debug)</summary>

```
MainWindow] <-2> 


m_currLang=[en]


[createModelTempDir] <-1> Created directory '/tmp/osmodel-65ba-ee9d-b2aa-353f-1725521247-0'
[initializeModelTempDir] <-2> Copying '/media/DataExt4/Software/Others/OSApp-build/_deps/openstudio-coalition-measures-src/models/ShoeboxExample.osm' to '/tmp/osmodel-65ba-ee9d-b2aa-353f-1725521247-0/ShoeboxExample.osm'
[initializeModelTempDir] <-2> Copying '/media/DataExt4/Software/Others/OSApp-build/_deps/openstudio-coalition-measures-src/models/ShoeboxExample' to '/tmp/osmodel-65ba-ee9d-b2aa-353f-1725521247-0/resources'
[attachWorkflow] <-2> Opened existing workflow.osw file
[openstudio.OSDocument] <-2> OSDocument::fixWeatherFileInTemp: 1
[openstudio.OSDocument] <-2> No need to copy weather file
[openstudio.LocalLibraryController] <-2> Creating LocalLibraryController with base app 0x7fffffffbf40
[utilities.bcl.BCLMeasure] <-2> Loading measures in path: /home/julien/OpenStudio/Measures_Temp
[utilities.bcl.BCLMeasure] <-2> Attempting to load measure: /home/julien/OpenStudio/Measures_Temp/show_case_geometry_diagnostics
[utilities.bcl.BCLMeasure] <-2> Success loading measure: /home/julien/OpenStudio/Measures_Temp/show_case_geometry_diagnostics
[openstudio.MeasureManager] <1> UUID of bcl measure at '/home/julien/BCL/a25386cd-60e4-46bc-8b11-c755f379d916/5b4d387a-f537-4693-a9eb-6192957b6c1b' conflicts with other bcl measure, measure at '/home/julien/BCL/a25386cd-60e4-46bc-8b11-c755f379d916/6b37673b-b0d8-4ab4-8f5a-0a48f170b4e8' will be used instead
[openstudio.openstudio_lib.MainRightColumnController] <-2> Setting new edit widget: 0x55555b691de0
[openstudio.openstudio_lib.MainRightColumnController] <-2> Removing old edit widget: 0x55555b691de0
[removeDir] <-2> Removed 240 files
[OpenStudioApplicationPathHelpers] <-2> getOpenStudioApplicationPath, info.dli_fname = '/media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp'
[PathHelpers] <-2> completeAndNormalize: result = /media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp-1.8.0-rc3
[ApplicationPathHelpers] <-2> getOpenStudioApplicationPath, found '/media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp-1.8.0-rc3'
[openstudio.completePathToFile] <-1> Path '/media/DataExt4/Software/Others/OpenStudioApplication/src/openstudio_app/Resources/ShoeboxModel/ShoeboxExample.osm' could not be resolved to an existing file. Returning an empty path.
[OpenStudioApplicationPathHelpers] <-2> getOpenStudioApplicationPath, info.dli_fname = '/media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp'
[PathHelpers] <-2> completeAndNormalize: result = /media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp-1.8.0-rc3
[ApplicationPathHelpers] <-2> getOpenStudioApplicationPath, found '/media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp-1.8.0-rc3'
[openstudio.osversion.VersionTranslator] <-2> Starting translation from Version 3.3.0.
[openstudio.osversion.VersionTranslator] <-2> Initial model has 20 objects.
[openstudio.osversion.VersionTranslator] <-2> Translation to 3.4.0 model has 20 objects.
[openstudio.osversion.VersionTranslator] <-2> Translation to 3.5.0 model has 20 objects.
[openstudio.osversion.VersionTranslator] <-2> Translation to 3.5.1 model has 20 objects.
[openstudio.osversion.VersionTranslator] <-2> Translation to 3.6.0 model has 20 objects.
[openstudio.osversion.VersionTranslator] <-2> Translation to 3.7.0 model has 20 objects.
[openstudio.osversion.VersionTranslator] <-2> Translation to 3.8.0 model has 20 objects.
[openstudio.osversion.VersionTranslator] <-2> Final model has 20 objects in IDF form.
[utilities.idf.Workspace] <-2> Workspace::isValid called.
[openstudio.osversion.VersionTranslator] <-2> Final model has 20 objects in Model form.
[OpenStudioApplicationPathHelpers] <-2> getOpenStudioApplicationPath, info.dli_fname = '/media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp'
[PathHelpers] <-2> completeAndNormalize: result = /media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp-1.8.0-rc3
[ApplicationPathHelpers] <-2> getOpenStudioApplicationPath, found '/media/DataExt4/Software/Others/OSApp-build/Products/OpenStudioApp-1.8.0-rc3'
[MainWindow] <-2> 


m_currLang=[en]


[createModelTempDir] <-1> Created directory '/tmp/osmodel-3f06-7bdb-5e3d-814c-1725521275-0'
[initializeModelTempDir] <-2> Copying '/media/DataExt4/Software/Others/OSApp-build/_deps/openstudio-coalition-measures-src/models/ShoeboxExample.osm' to '/tmp/osmodel-3f06-7bdb-5e3d-814c-1725521275-0/ShoeboxExample.osm'
[initializeModelTempDir] <-2> Copying '/media/DataExt4/Software/Others/OSApp-build/_deps/openstudio-coalition-measures-src/models/ShoeboxExample' to '/tmp/osmodel-3f06-7bdb-5e3d-814c-1725521275-0/resources'
[attachWorkflow] <-2> Opened existing workflow.osw file
[openstudio.OSDocument] <-2> OSDocument::fixWeatherFileInTemp: 1
[openstudio.OSDocument] <-2> No need to copy weather file
[openstudio.LocalLibraryController] <-2> Creating LocalLibraryController with base app 0x7fffffffbf40
Process 13988 stopped
* thread #1, name = 'OpenStudioApp', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x90)
    frame #0: 0x0000555555a5aec0 OpenStudioApp`openstudio::OSDocument::mainWindow(this=0x0000000000000000) at OSDocument.cpp:262:10
   259 	}
   260 	
   261 	MainWindow* OSDocument::mainWindow() {
-> 262 	  return m_mainWindow;
   263 	}
   264 	
   265 	model::Model OSDocument::model() {
(lldb) bt
error: OpenStudioApp 0x007a4683: DW_TAG_member 'data' refers to type 0x00000000007d177a which extends beyond the bounds of 0x007a4674
* thread #1, name = 'OpenStudioApp', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x90)
  * frame #0: 0x0000555555a5aec0 OpenStudioApp`openstudio::OSDocument::mainWindow(this=0x0000000000000000) at OSDocument.cpp:262:10
    frame #1: 0x0000555555f113c5 OpenStudioApp`openstudio::LibraryItemDelegate::view(this=0x0000555558afb3a0, dataSource=QSharedPointer<openstudio::OSListItem> @ 0x00007fffffff9560) at LocalLibraryController.cpp:500:101
    frame #2: 0x0000555555bff7dd OpenStudioApp`openstudio::OSListView::insertItemView(this=0x000055555c47a980, i=0) at OSListView.cpp:151:39
    frame #3: 0x0000555555bff6c5 OpenStudioApp`openstudio::OSListView::refreshAllViews(this=0x000055555c47a980) at OSListView.cpp:139:21
    frame #4: 0x0000555555bff23b OpenStudioApp`openstudio::OSListView::setDelegate(this=0x000055555c47a980, delegate=QSharedPointer<openstudio::OSItemDelegate> @ 0x00007fffffff9690) at OSListView.cpp:95:20
    frame #5: 0x0000555555f0fad6 OpenStudioApp`openstudio::LibrarySubGroupItemDelegate::view(this=0x000055555b28d990, dataSource=QSharedPointer<openstudio::OSListItem> @ 0x00007fffffff9730) at LocalLibraryController.cpp:337:33
    frame #6: 0x0000555555bff7dd OpenStudioApp`openstudio::OSListView::insertItemView(this=0x0000555558840700, i=0) at OSListView.cpp:151:39
    frame #7: 0x0000555555bff6c5 OpenStudioApp`openstudio::OSListView::refreshAllViews(this=0x0000555558840700) at OSListView.cpp:139:21
    frame #8: 0x0000555555bff23b OpenStudioApp`openstudio::OSListView::setDelegate(this=0x0000555558840700, delegate=QSharedPointer<openstudio::OSItemDelegate> @ 0x00007fffffff9860) at OSListView.cpp:95:20
    frame #9: 0x0000555555f0f28e OpenStudioApp`openstudio::LibraryGroupItemDelegate::view(this=0x0000555559b2af80, dataSource=QSharedPointer<openstudio::OSListItem> @ 0x00007fffffff9900) at LocalLibraryController.cpp:278:34
    frame #10: 0x0000555555bff7dd OpenStudioApp`openstudio::OSListView::insertItemView(this=0x000055555b051290, i=0) at OSListView.cpp:151:39
    frame #11: 0x0000555555bff6c5 OpenStudioApp`openstudio::OSListView::refreshAllViews(this=0x000055555b051290) at OSListView.cpp:139:21
    frame #12: 0x0000555555bff23b OpenStudioApp`openstudio::OSListView::setDelegate(this=0x000055555b051290, delegate=QSharedPointer<openstudio::OSItemDelegate> @ 0x00007fffffff9a30) at OSListView.cpp:95:20
    frame #13: 0x0000555555f0eaf5 OpenStudioApp`openstudio::LibraryTypeItemDelegate::view(this=0x000055555c66ed40, dataSource=QSharedPointer<openstudio::OSListItem> @ 0x00007fffffff9ab0) at LocalLibraryController.cpp:219:31
    frame #14: 0x0000555555bff7dd OpenStudioApp`openstudio::OSListView::insertItemView(this=0x000055555aae52a0, i=0) at OSListView.cpp:151:39
    frame #15: 0x0000555555bff6c5 OpenStudioApp`openstudio::OSListView::refreshAllViews(this=0x000055555aae52a0) at OSListView.cpp:139:21
    frame #16: 0x0000555555bff4cc OpenStudioApp`openstudio::OSListView::setListController(this=0x000055555aae52a0, listController=QSharedPointer<openstudio::OSListController> @ 0x00007fffffff9d10) at OSListView.cpp:110:18
    frame #17: 0x0000555555f0d113 OpenStudioApp`openstudio::LocalLibraryController::LocalLibraryController(this=0x000055555cc86d60, t_app=0x00007fffffffbf30, onlyShowModelMeasures=false) at LocalLibraryController.cpp:67:33
    frame #18: 0x0000555555ce5a28 OpenStudioApp`openstudio::MainRightColumnController::MainRightColumnController(this=0x000055555db74130, model=0x000055555d3124c0, resourcesPath=0x000055555d3124f0) at MainRightColumnController.cpp:48:80
    frame #19: 0x0000555555a80e51 OpenStudioApp`decltype(::new((void*)(0)) openstudio::MainRightColumnController(declval<openstudio::model::Model&>(), declval<boost::filesystem::path&>())) std::construct_at<openstudio::MainRightColumnController, openstudio::model::Model&, boost::filesystem::path&>(__location=0x000055555db74130, (null)=0x000055555d3124c0, (null)=0x000055555d3124f0) at stl_construct.h:97:14
    frame #20: 0x0000555555a80ecd OpenStudioApp`void std::allocator_traits<std::allocator<openstudio::MainRightColumnController>>::construct<openstudio::MainRightColumnController, openstudio::model::Model&, boost::filesystem::path&>(__a=0x00007fffffffa15f, __p=0x000055555db74130, (null)=0x000055555d3124c0, (null)=0x000055555d3124f0) at alloc_traits.h:514:21
    frame #21: 0x0000555555a7e3a5 OpenStudioApp`std::_Sp_counted_ptr_inplace<openstudio::MainRightColumnController, std::allocator<openstudio::MainRightColumnController>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<openstudio::model::Model&, boost::filesystem::path&>(this=0x000055555db74120, __a=allocator<openstudio::MainRightColumnController> @ 0x00007fffffffa15f, (null)=0x000055555d3124c0, (null)=0x000055555d3124f0) at shared_ptr_base.h:551:39
    frame #22: 0x0000555555a7b359 OpenStudioApp`std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<openstudio::MainRightColumnController, std::allocator<openstudio::MainRightColumnController>, openstudio::model::Model&, boost::filesystem::path&>(this=0x00007fffffffa398, __p=0x00007fffffffa390, __a=_Sp_alloc_shared_tag<std::allocator<openstudio::MainRightColumnController> > @ 0x00007fffffffa138, (null)=0x000055555d3124c0, (null)=0x000055555d3124f0) at shared_ptr_base.h:682:16
    frame #23: 0x0000555555a76ed0 OpenStudioApp`std::__shared_ptr<openstudio::MainRightColumnController, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<openstudio::MainRightColumnController>, openstudio::model::Model&, boost::filesystem::path&>(this=0x00007fffffffa390, __tag=_Sp_alloc_shared_tag<std::allocator<openstudio::MainRightColumnController> > @ 0x00007fffffffa1e0, (null)=0x000055555d3124c0, (null)=0x000055555d3124f0) at shared_ptr_base.h:1376:71
    frame #24: 0x0000555555a73411 OpenStudioApp`std::shared_ptr<openstudio::MainRightColumnController>::shared_ptr<std::allocator<openstudio::MainRightColumnController>, openstudio::model::Model&, boost::filesystem::path&>(this=nullptr, __tag=_Sp_alloc_shared_tag<std::allocator<openstudio::MainRightColumnController> > @ 0x00007fffffffa220, (null)=0x000055555d3124c0, (null)=0x000055555d3124f0) at shared_ptr.h:408:59
    frame #25: 0x0000555555a6f679 OpenStudioApp`std::shared_ptr<openstudio::MainRightColumnController> std::allocate_shared<openstudio::MainRightColumnController, std::allocator<openstudio::MainRightColumnController>, openstudio::model::Model&, boost::filesystem::path&>(__a=0x00007fffffffa2b7, (null)=0x000055555d3124c0, (null)=0x000055555d3124f0) at shared_ptr.h:862:39
    frame #26: 0x0000555555a6bcc0 OpenStudioApp`std::shared_ptr<openstudio::MainRightColumnController> std::make_shared<openstudio::MainRightColumnController, openstudio::model::Model&, boost::filesystem::path&>((null)=0x000055555d3124c0, (null)=0x000055555d3124f0) at shared_ptr.h:878:42
    frame #27: 0x0000555555a5b21f OpenStudioApp`openstudio::OSDocument::setModel(this=0x000055555d312480, model=0x00007fffffffaaa8, modified=false, (null)=false) at OSDocument.cpp:302:76
    frame #28: 0x0000555555a59493 OpenStudioApp`openstudio::OSDocument::OSDocument(this=0x000055555d312480, library=0x00007fffffffafd0, resourcesPath=0x00007fffffffb090, model=openstudio::model::OptionalModel @ 0x00007fffffffaaa0, filePath=QString @ 0x00007fffffffaa80, isPlugin=false, startTabIndex=0, startSubTabIndex=0) at OSDocument.cpp:167:11
    frame #29: 0x0000555555a3d645 OpenStudioApp`decltype(::new((void*)(0)) openstudio::OSDocument(declval<openstudio::model::Model>(), declval<boost::filesystem::path>(), declval<boost::optional<openstudio::model::Model>&>(), declval<QString>(), declval<bool>(), declval<int>())) std::construct_at<openstudio::OSDocument, openstudio::model::Model, boost::filesystem::path, boost::optional<openstudio::model::Model>&, QString, bool, int>(__location=0x000055555d312480, (null)=0x00007fffffffafd0, (null)=0x00007fffffffb090, (null)=0x00007fffffffb030, (null)=0x00007fffffffaff0, (null)=0x00007fffffffafba, (null)=0x00007fffffffafbc) at stl_construct.h:97:14
    frame #30: 0x0000555555a3d762 OpenStudioApp`void std::allocator_traits<std::allocator<openstudio::OSDocument>>::construct<openstudio::OSDocument, openstudio::model::Model, boost::filesystem::path, boost::optional<openstudio::model::Model>&, QString, bool, int>(__a=0x00007fffffffaccf, __p=0x000055555d312480, (null)=0x00007fffffffafd0, (null)=0x00007fffffffb090, (null)=0x00007fffffffb030, (null)=0x00007fffffffaff0, (null)=0x00007fffffffafba, (null)=0x00007fffffffafbc) at alloc_traits.h:514:21
    frame #31: 0x0000555555a3b09c OpenStudioApp`std::_Sp_counted_ptr_inplace<openstudio::OSDocument, std::allocator<openstudio::OSDocument>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<openstudio::model::Model, boost::filesystem::path, boost::optional<openstudio::model::Model>&, QString, bool, int>(this=0x000055555d312470, __a=allocator<openstudio::OSDocument> @ 0x00007fffffffaccf, (null)=0x00007fffffffafd0, (null)=0x00007fffffffb090, (null)=0x00007fffffffb030, (null)=0x00007fffffffaff0, (null)=0x00007fffffffafba, (null)=0x00007fffffffafbc) at shared_ptr_base.h:551:39
    frame #32: 0x0000555555a3854a OpenStudioApp`std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<openstudio::OSDocument, std::allocator<openstudio::OSDocument>, openstudio::model::Model, boost::filesystem::path, boost::optional<openstudio::model::Model>&, QString, bool, int>(this=0x00007fffffffafc8, __p=0x00007fffffffafc0, __a=_Sp_alloc_shared_tag<std::allocator<openstudio::OSDocument> > @ 0x00007fffffffaca8, (null)=0x00007fffffffafd0, (null)=0x00007fffffffb090, (null)=0x00007fffffffb030, (null)=0x00007fffffffaff0, (null)=0x00007fffffffafba, (null)=0x00007fffffffafbc) at shared_ptr_base.h:682:16
    frame #33: 0x0000555555a35369 OpenStudioApp`std::__shared_ptr<openstudio::OSDocument, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<openstudio::OSDocument>, openstudio::model::Model, boost::filesystem::path, boost::optional<openstudio::model::Model>&, QString, bool, int>(this=0x00007fffffffafc0, __tag=_Sp_alloc_shared_tag<std::allocator<openstudio::OSDocument> > @ 0x00007fffffffad90, (null)=0x00007fffffffafd0, (null)=0x00007fffffffb090, (null)=0x00007fffffffb030, (null)=0x00007fffffffaff0, (null)=0x00007fffffffafba, (null)=0x00007fffffffafbc) at shared_ptr_base.h:1376:71
    frame #34: 0x0000555555a31980 OpenStudioApp`std::shared_ptr<openstudio::OSDocument>::shared_ptr<std::allocator<openstudio::OSDocument>, openstudio::model::Model, boost::filesystem::path, boost::optional<openstudio::model::Model>&, QString, bool, int>(this=nullptr, __tag=_Sp_alloc_shared_tag<std::allocator<openstudio::OSDocument> > @ 0x00007fffffffae20, (null)=0x00007fffffffafd0, (null)=0x00007fffffffb090, (null)=0x00007fffffffb030, (null)=0x00007fffffffaff0, (null)=0x00007fffffffafba, (null)=0x00007fffffffafbc) at shared_ptr.h:408:59
    frame #35: 0x0000555555a2d453 OpenStudioApp`std::shared_ptr<openstudio::OSDocument> std::allocate_shared<openstudio::OSDocument, std::allocator<openstudio::OSDocument>, openstudio::model::Model, boost::filesystem::path, boost::optional<openstudio::model::Model>&, QString, bool, int>(__a=0x00007fffffffaf47, (null)=0x00007fffffffafd0, (null)=0x00007fffffffb090, (null)=0x00007fffffffb030, (null)=0x00007fffffffaff0, (null)=0x00007fffffffafba, (null)=0x00007fffffffafbc) at shared_ptr.h:862:39
    frame #36: 0x0000555555a28822 OpenStudioApp`std::shared_ptr<openstudio::OSDocument> std::make_shared<openstudio::OSDocument, openstudio::model::Model, boost::filesystem::path, boost::optional<openstudio::model::Model>&, QString, bool, int>((null)=0x00007fffffffafd0, (null)=0x00007fffffffb090, (null)=0x00007fffffffb030, (null)=0x00007fffffffaff0, (null)=0x00007fffffffafba, (null)=0x00007fffffffafbc) at shared_ptr.h:878:42
    frame #37: 0x0000555555a1c58c OpenStudioApp`openstudio::OpenStudioApp::loadShoeboxModel(this=0x00007fffffffbf30) at OpenStudioApp.cpp:1563:48
    frame #38: 0x0000555555a39602 OpenStudioApp`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (openstudio::OpenStudioApp::*)()>::call(f=(OpenStudioApp`openstudio::OpenStudioApp::loadShoeboxModel() at OpenStudioApp.cpp:1539:40), o=0x00007fffffffbf30, arg=0x00007fffffffb390) at qobjectdefs_impl.h:145:20
    frame #39: 0x0000555555a3620a OpenStudioApp`void QtPrivate::FunctionPointer<void (openstudio::OpenStudioApp::*)()>::call<QtPrivate::List<>, void>(f=(OpenStudioApp`openstudio::OpenStudioApp::loadShoeboxModel() at OpenStudioApp.cpp:1539:40), o=0x00007fffffffbf30, arg=0x00007fffffffb390) at qobjectdefs_impl.h:182:95
    frame #40: 0x0000555555a3352b OpenStudioApp`QtPrivate::QCallableObject<void (openstudio::OpenStudioApp::*)(), QtPrivate::List<>, void>::impl(which=1, this_=0x000055555d5f32d0, r=0x00007fffffffbf30, a=0x00007fffffffb390, ret=0x0000000000000000) at qobjectdefs_impl.h:520:53
    frame #41: 0x00007fffe2d33cd2 libQt6Core.so.6`void doActivate<false>(QObject*, int, void**) [inlined] QtPrivate::QSlotObjectBase::call(a=0x00007fffffffb390, r=0x00007fffffffbf30, this=<unavailable>) at qobjectdefs_impl.h:433:57
    frame #42: 0x00007fffe2d33cbc libQt6Core.so.6`void doActivate<false>(sender=0x000055555c6e2700, signal_index=15, argv=0x00007fffffffb390) at qobject.cpp:4039:30
    frame #43: 0x0000555555c34587 OpenStudioApp`openstudio::OSDocument::loadShoeboxModelClicked(this=0x000055555c6e2700) at moc_OSDocument.cpp:995:26
    frame #44: 0x0000555555a3c7c8 OpenStudioApp`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (openstudio::OSDocument::*)()>::call(f=(OpenStudioApp`openstudio::OSDocument::loadShoeboxModelClicked() at moc_OSDocument.cpp:994:1), o=0x000055555c6e2700, arg=0x00007fffffffb540) at qobjectdefs_impl.h:145:20
    frame #45: 0x0000555555a39e06 OpenStudioApp`void QtPrivate::FunctionPointer<void (openstudio::OSDocument::*)()>::call<QtPrivate::List<>, void>(f=(OpenStudioApp`openstudio::OSDocument::loadShoeboxModelClicked() at moc_OSDocument.cpp:994:1), o=0x000055555c6e2700, arg=0x00007fffffffb540) at qobjectdefs_impl.h:182:95
    frame #46: 0x0000555555a36cb3 OpenStudioApp`QtPrivate::QCallableObject<void (openstudio::OSDocument::*)(), QtPrivate::List<>, void>::impl(which=1, this_=0x000055555d5f1f50, r=0x000055555c6e2700, a=0x00007fffffffb540, ret=0x0000000000000000) at qobjectdefs_impl.h:520:53
    frame #47: 0x00007fffe2d33cd2 libQt6Core.so.6`void doActivate<false>(QObject*, int, void**) [inlined] QtPrivate::QSlotObjectBase::call(a=0x00007fffffffb540, r=0x000055555c6e2700, this=<unavailable>) at qobjectdefs_impl.h:433:57
    frame #48: 0x00007fffe2d33cbc libQt6Core.so.6`void doActivate<false>(sender=0x000055555d5cc550, signal_index=26, argv=0x00007fffffffb540) at qobject.cpp:4039:30
    frame #49: 0x0000555555c30495 OpenStudioApp`openstudio::MainWindow::loadShoeboxModelClicked(this=0x000055555d5cc550) at moc_MainWindow.cpp:1131:26
    frame #50: 0x0000555555d0ab7b OpenStudioApp`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (openstudio::MainWindow::*)()>::call(f=(OpenStudioApp`openstudio::MainWindow::loadShoeboxModelClicked() at moc_MainWindow.cpp:1130:1), o=0x000055555d5cc550, arg=0x00007fffffffb6f0) at qobjectdefs_impl.h:145:20
    frame #51: 0x0000555555d0a12c OpenStudioApp`void QtPrivate::FunctionPointer<void (openstudio::MainWindow::*)()>::call<QtPrivate::List<>, void>(f=(OpenStudioApp`openstudio::MainWindow::loadShoeboxModelClicked() at moc_MainWindow.cpp:1130:1), o=0x000055555d5cc550, arg=0x00007fffffffb6f0) at qobjectdefs_impl.h:182:95
    frame #52: 0x0000555555d09ad7 OpenStudioApp`QtPrivate::QCallableObject<void (openstudio::MainWindow::*)(), QtPrivate::List<>, void>::impl(which=1, this_=0x000055555c407840, r=0x000055555d5cc550, a=0x00007fffffffb6f0, ret=0x0000000000000000) at qobjectdefs_impl.h:520:53
    frame #53: 0x00007fffe2d33cd2 libQt6Core.so.6`void doActivate<false>(QObject*, int, void**) [inlined] QtPrivate::QSlotObjectBase::call(a=0x00007fffffffb6f0, r=0x000055555d5cc550, this=<unavailable>) at qobjectdefs_impl.h:433:57
    frame #54: 0x00007fffe2d33cbc libQt6Core.so.6`void doActivate<false>(sender=0x000055555cee49c0, signal_index=21, argv=0x00007fffffffb6f0) at qobject.cpp:4039:30
    frame #55: 0x0000555555f7e39d OpenStudioApp`openstudio::MainMenu::loadShoeboxModelClicked(this=0x000055555cee49c0) at moc_MainMenu.cpp:1081:26
    frame #56: 0x00005555560fbb35 OpenStudioApp`QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (openstudio::MainMenu::*)()>::call(f=(OpenStudioApp`openstudio::MainMenu::loadShoeboxModelClicked() at moc_MainMenu.cpp:1080:1), o=0x000055555cee49c0, arg=0x000055555dc097b8) at qobjectdefs_impl.h:145:20
    frame #57: 0x00005555560fb9ae OpenStudioApp`void QtPrivate::FunctionPointer<void (openstudio::MainMenu::*)()>::call<QtPrivate::List<>, void>(f=(OpenStudioApp`openstudio::MainMenu::loadShoeboxModelClicked() at moc_MainMenu.cpp:1080:1), o=0x000055555cee49c0, arg=0x000055555dc097b8) at qobjectdefs_impl.h:182:95
    frame #58: 0x00005555560fb7a3 OpenStudioApp`QtPrivate::QCallableObject<void (openstudio::MainMenu::*)(), QtPrivate::List<>, void>::impl(which=1, this_=0x000055555b3375a0, r=0x000055555cee49c0, a=0x000055555dc097b8, ret=0x0000000000000000) at qobjectdefs_impl.h:520:53
    frame #59: 0x00007fffe2d257e0 libQt6Core.so.6`QObject::event(this=0x000055555cee49c0, e=0x000055555dc09770) at qobject.cpp:1437:31
    frame #60: 0x00007fffe3d8b012 libQt6Widgets.so.6`QApplicationPrivate::notify_helper(this=<unavailable>, receiver=0x000055555cee49c0, e=0x000055555dc09770) at qapplication.cpp:3296:31
    frame #61: 0x0000555555a569ab OpenStudioApp`openstudio::OSAppBase::notify(this=0x00007fffffffbf30, receiver=0x000055555cee49c0, e=0x000055555dc09770) at OSAppBase.cpp:54:30
    frame #62: 0x0000555555a15709 OpenStudioApp`openstudio::OpenStudioApp::notify(this=0x00007fffffffbf30, receiver=0x000055555cee49c0, event=0x000055555dc09770) at OpenStudioApp.cpp:1055:27
    frame #63: 0x00007fffe2cd76da libQt6Core.so.6`QCoreApplication::notifyInternal2(receiver=0x000055555cee49c0, event=0x00005555592ba4d0) at qcoreapplication.cpp:1121:24
```

```
(lldb) p m_mainWindow
error: OpenStudioApp 0x037d6f58: DW_TAG_member '_M_local_buf' refers to type 0x00000000037fbba5 which extends beyond the bounds of 0x037d6f4e
error: Couldn't apply expression side effects : Couldn't dematerialize a result variable: couldn't read its memory

(lldb) p this
(openstudio::OSDocument *const) nullptr
```

</details>

## Steps to Reproduce

1. Open OpenStudioApp
2. Do File > Examples > Shoebox model until it crashes

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):

### PR DESCRIPTION
**Pull request by jmarrec**
- Fix #747 (hopefully)
- Fix a crash when you try to load the Shoebox model from the Workflow/Measures tab

### CODE REVIEW

**Comment by jmarrec** [comment]
cannot reproduce crash on macOs either

File: src/openstudio_app/OpenStudioApp.cpp [hunk 1]
```diff
@@ -1553,14 +1553,16 @@ void OpenStudioApp::loadShoeboxModel() {
   versionTranslator.setAllowNewerVersions(false);
 
   auto filePath = resourcesPath() / toPath("ShoeboxModel/ShoeboxExample.osm");
-  boost::optional<openstudio::model::Model> model = versionTranslator.loadModel(filePath);
-  if (!model && isOpenStudioApplicationRunningFromBuildDirectory()) {
+  boost::optional<openstudio::model::Model> model_;
+  if (openstudio::filesystem::is_regular_file(filePath)) {
```
Comment (macumber) [inline src/openstudio_app/OpenStudioApp.cpp:1557]: Was this the line that prevents the crash?

Comment (jmarrec) [reply src/openstudio_app/OpenStudioApp.cpp:1557]: currentDocument not null.

Comment (jmarrec) [reply src/openstudio_app/OpenStudioApp.cpp:1557]: This specific change is mostly because I found it annoying and counterproductive to try to load a model and get a warning/error on the console like "Cannot resolve path 'xxxx', model can't be loaded".

Comment (jmarrec) [reply src/openstudio_app/OpenStudioApp.cpp:1557]: https://github.com/NREL/OpenStudio/blob/ba1b94b6542c1f1d4cdcdb775886852b9a82bc4f/src/model/Model.cpp#L1848
