### PR TITLE
Show empty required object-list fields with warning icon, remove unused IGdefaultRemoved slot

### LINKED ISSUE #778: Unable to assign zone name to Refrigeration:Case
Issue overview
--------------

Toggling the Zone Name drop down does not update the zone name for Refrigeration:Case object.
image
image

## Steps to Reproduce

Here is a sample .osm file: 
[file f1basic dr-badran.osm.txt](https://github.com/user-attachments/files/18265071/file.f1basic.dr-badran.osm.txt)

1.
2.
3.
4.

## Details
If another thermal zone is added to the project, one can toggle the drop down, select the other thermal zone, then toggle the drop down again and select the correct thermal zone to get OpenStudio to write to the .osm file.
### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of OpenStudioApplication (if using an intermediate build, include SHA):
image

### PR DESCRIPTION
**Pull request by macumber**
Fixes #778

### CODE REVIEW

File: src/model_editor/InspectorGadget.cpp [hunk 1]
```diff
@@ -789,9 +789,12 @@ void InspectorGadget::layoutComboBox(QVBoxLayout* layout, QWidget* parent, opens
   int idx = combo->findText(curVal.c_str(), Qt::MatchFixedString);
 
   if (-1 == idx) {
+
+    // field is currently set to an invalid value
     idx = 0;
-    connect(combo, static_cast<void (QComboBox::*)(const QString&)>(&QComboBox::currentTextChanged), this, &InspectorGadget::IGdefaultRemoved);
```
Comment (macumber) [inline src/model_editor/InspectorGadget.cpp:793]: The `IGdefaultRemoved` slot was only connected in this case and it was being called directly from `InspectorGadget::layoutComboBox` at line 808 ` combo->setCurrentIndex(idx)`.  This means that the slot was called before the user had a chance to do anything.

**Comment by jmarrec** [comment]
@macumber A before/after screenshot or gif would go a long way in helping to see the changes when reviewing.

**Comment by jmarrec** [comment]
I'm not seeing any icons. Model with zero thermal zones:

image

One thermal zone: it defaults to "Thermal Zone 1"

image

**Comment by jmarrec** [comment]
**After, this PR**

Model with no thermal zone:

image

**Comment by macumber** [comment]
I saw the same issue and figured that behavior was probably better than whatever bugs I would introduce trying to clean up the combo box list when the user picked a new option.  I heard you on the gifs for PRs, I'll try to be better :-)
