### PR TITLE
Fix #476 - Apply to selected does not work on ThermalZone Cooling or Heating Size Parameters

### LINKED ISSUE #476: Apply to selected does not work on ThermalZone Cooling or Heating Size Parameters
Issue overview
--------------
Changes are applied but do not update until changing tabs. Likely need to add additional objects to watch on this tab

### PR DESCRIPTION
**Pull request by jmarrec**
* Fix #476

### CODE REVIEW

File: src/openstudio_lib/ThermalZonesGridView.cpp [hunk 1]
```diff
@@ -213,6 +213,25 @@ void ThermalZonesGridController::addColumns(const QString& /*category*/, std::ve
...
+  // trigger a nano_emit for the TZ
+  // eg: `makeProxyAdapterForceRefresh(&model::SizingZone::setZoneCoolingDesignSupplyAirTemperature)` will return
+  //   ```
+  //   std::function<bool(model::ThermalZone*, double val)>([](model::ThermalZone* t_z, double val) {
+  //     bool b = t_z->sizingZone().setZoneCoolingDesignSupplyAirTemperature(val);
+  //     t_z->getImpl<openstudio::model::detail::ModelObject_Impl>()->onChange.nano_emit();
+  //     return b;
+  //   })
+  //   ```
+  using SizingZoneMemberFn = bool (model::SizingZone::*)(double);
```
Comment (macumber) [inline src/openstudio_lib/ThermalZonesGridView.cpp:226]: This is actually pretty good, the comments help a lot.

**Review by macumber — APPROVED** [review]
Looks good to me if it works
